name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  flutter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: Instalar dependências
        run: flutter pub get
      - name: Análise estática
        run: flutter analyze
      - name: Testes
        run: flutter test
